### ISSUE TITLE
Final instructions from dorm operators

### ISSUE THREAD

**Issue by shihchengyen** [Jermyn/Indoor-Localisation#29]
Dashboard:
Mike, Tushar, Robin

SMS notification after 1st time detection of abnormal readings:
Robin, Saraa [Worker will get a notification]

SMS notification for reminder to take readings again after 60 mins:
Robin, Saraa [Worker will get reminder as well]

SMS notification if the 2nd reading is normal:
Robin, Saraa [Along with Worker to get notification saying - Safe reading]

SMS notification after the 2nd reading is also abnormal:
Mike, Robin, Saraa, Tushar [Worker to get a notification saying - contact dorm incharge through phone call]

Phone Numbers:
Mike - 90468811
Tushar - 97568463
Robin - 87493007
Saraa - 87529400

**Comment by Jermyn** [comment]
I assume there isn't a need to send sms if first reading is normal?

So these 4 names are the actual residents we will be testing on? If so, we need to know the other info such as room, bed and devices assigned.

can let me know the exact contents of the messages, especially the other languages.

**Comment by shihchengyen** [comment]
No, no need to send SMS if the reading is normal.

Those 4 names are the dorm operators. We will be getting the information on the residents later.

I have updated the text of the messages in Issue #16

**Comment by Jermyn** [comment]
How about the sms message to operator when the worker did not send any readings after the sms message to retake his measurements? Which operator do we send the sms to?

**Comment by Jermyn** [comment]
SMS notification for reminder to take readings again after 60 mins:
Robin, Saraa [Worker will get reminder as well]

For this part, if we send the sms to the operators, they wouldn't know who is it about as there are no names in this text. Is that okay for them?

**Comment by shihchengyen** [comment]
They now think that the operator does not need to get the reminder. Just sending it to the resident is sufficient.

**Comment by shihchengyen** [comment]
>> How about the sms message to operator when the worker did not send any readings after the >> sms message to retake his measurements? Which operator do we send the sms to?

Robin, Saraa
